name: metis-sepolia

services:
  l2geth:
    image: metisdao/l2geth:v0.1.2
    container_name: l2geth
    restart: unless-stopped
    network_mode: host
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD-SHELL", "is-l2geth-stalled"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    env_file:
      - l2geth.env
    volumes:
      - "{{ SEPOLIA_PATH }}/l2geth:/root/.ethereum"
    logging:
      driver: json-file
      options:
        max-size: 2m
        max-file: 10
